export function getDemoData() {
  // Dates relative to today so demo data never expires
  const today = new Date()
  const fmt = (d) => d.toISOString().split('T')[0]
  const addDays = (d, n) => { const r = new Date(d); r.setDate(r.getDate() + n); return r }
  const subDays = (d, n) => addDays(d, -n)

  const clientes = [
    {
      id: 'c1',
      nombre: 'María Rodríguez Pérez',
      apodo: 'Maruca',
      telefono: '809-555-1234',
      celular: '829-555-1234',
      dni: '001-1234567-8',
      direccion: 'Calle Principal #45, Los Alcarrizos, Santo Domingo Oeste',
      garante: 'Juan Rodríguez',
      referencia: 'Vecina de la calle 5',
      notas: 'Paga puntual. Trabaja en el mercado.',
      fechaCreacion: '2024-11-10',
      documentos: [],
    },
    {
      id: 'c2',
      nombre: 'Pedro Antonio Medina',
      apodo: 'Peteco',
      telefono: '809-555-2345',
      celular: '849-555-2345',
      dni: '001-2345678-9',
      direccion: 'Av. Independencia #120, Santiago de los Caballeros',
      garante: 'Carmen Medina',
      referencia: 'Referido por María Rodríguez',
      notas: 'Tiene negocio propio de ferretería.',
      fechaCreacion: '2024-12-01',
      documentos: [],
    },
    {
      id: 'c3',
      nombre: 'Ana Luisa Fernández',
      apodo: 'Anita',
      telefono: '809-555-3456',
      celular: '829-555-3456',
      dni: '001-3456789-0',
      direccion: 'Los Jardines del Norte, Bloque 3, Santo Domingo Norte',
      garante: 'Luis Fernández',
      referencia: 'Empleada en el hospital',
      notas: 'Enfermera. Salario fijo quincenal.',
      fechaCreacion: '2024-12-15',
      documentos: [],
    },
    {
      id: 'c4',
      nombre: 'Carlos Emilio Santana',
      apodo: 'Carlitos',
      telefono: '809-555-4567',
      celular: '849-555-4567',
      dni: '001-4567890-1',
      direccion: 'Sector La Fe #88, Distrito Nacional',
      garante: '',
      referencia: 'Conocido personal',
      notas: 'Tiene atraso en pagos anteriores. Vigilar.',
      fechaCreacion: '2025-01-05',
      documentos: [],
    },
    {
      id: 'c5',
      nombre: 'Rosa Elena Jiménez',
      apodo: 'Rosita',
      telefono: '809-555-5678',
      celular: '829-555-5678',
      dni: '001-5678901-2',
      direccion: 'Calle 10 #22, Villa Mella, Santo Domingo Norte',
      garante: 'Francisco Jiménez',
      referencia: 'Prima de Ana Fernández',
      notas: 'Tiene colmado. Buenos pagos.',
      fechaCreacion: '2025-01-20',
      documentos: [],
    },
  ]

  const prestamos = [
    {
      id: 'p1',
      clienteId: 'c1',
      monto: 50000,
      interes: 10,
      tipoInteres: 'mensual',
      fechaInicio: fmt(subDays(today, 45)),
      fechaVencimiento: fmt(addDays(today, 135)),
      frecuencia: 'semanal',
      cuotas: 24,
      estado: 'activo',
      notas: 'Para mejoras del negocio',
    },
    {
      id: 'p2',
      clienteId: 'c1',
      monto: 20000,
      interes: 8,
      tipoInteres: 'fijo',
      fechaInicio: fmt(subDays(today, 120)),
      fechaVencimiento: fmt(subDays(today, 30)),
      frecuencia: 'mensual',
      cuotas: 3,
      estado: 'pagado',
      notas: 'Primer préstamo, pagado completo',
    },
    {
      id: 'p3',
      clienteId: 'c2',
      monto: 150000,
      interes: 12,
      tipoInteres: 'mensual',
      fechaInicio: fmt(subDays(today, 60)),
      fechaVencimiento: fmt(addDays(today, 120)),
      frecuencia: 'mensual',
      cuotas: 6,
      estado: 'activo',
      notas: 'Ampliación de ferretería',
    },
    {
      id: 'p4',
      clienteId: 'c3',
      monto: 30000,
      interes: 10,
      tipoInteres: 'mensual',
      fechaInicio: fmt(subDays(today, 50)),
      fechaVencimiento: fmt(addDays(today, 130)),
      frecuencia: 'quincenal',
      cuotas: 12,
      estado: 'activo',
      notas: 'Para gastos del hogar',
    },
    {
      id: 'p5',
      clienteId: 'c4',
      monto: 75000,
      interes: 15,
      tipoInteres: 'mensual',
      fechaInicio: fmt(subDays(today, 90)),
      fechaVencimiento: fmt(subDays(today, 5)),
      frecuencia: 'mensual',
      cuotas: 3,
      estado: 'vencido',
      notas: 'Vencido sin pagar. En seguimiento.',
    },
    {
      id: 'p6',
      clienteId: 'c5',
      monto: 25000,
      interes: 10,
      tipoInteres: 'mensual',
      fechaInicio: fmt(subDays(today, 30)),
      fechaVencimiento: fmt(addDays(today, 150)),
      frecuencia: 'semanal',
      cuotas: 24,
      estado: 'activo',
      notas: 'Para surtir el colmado',
    },
    {
      id: 'p7',
      clienteId: 'c2',
      monto: 80000,
      interes: 10,
      tipoInteres: 'fijo',
      fechaInicio: fmt(subDays(today, 180)),
      fechaVencimiento: fmt(subDays(today, 90)),
      frecuencia: 'mensual',
      cuotas: 3,
      estado: 'pagado',
      notas: 'Préstamo anterior pagado',
    },
    {
      id: 'p8',
      clienteId: 'c3',
      monto: 10000,
      interes: 5,
      tipoInteres: 'fijo',
      fechaInicio: fmt(subDays(today, 20)),
      fechaVencimiento: fmt(addDays(today, 70)),
      frecuencia: 'mensual',
      cuotas: 3,
      estado: 'activo',
      notas: 'Pequeño préstamo personal',
    },
  ]

  const pagos = [
    { id: 'pg1',  prestamoId: 'p1', clienteId: 'c1', monto: 3000,  fecha: fmt(subDays(today, 38)), metodo: 'efectivo',     nota: 'Pago cuota 1' },
    { id: 'pg2',  prestamoId: 'p1', clienteId: 'c1', monto: 3000,  fecha: fmt(subDays(today, 31)), metodo: 'efectivo',     nota: 'Pago cuota 2' },
    { id: 'pg3',  prestamoId: 'p1', clienteId: 'c1', monto: 3000,  fecha: fmt(subDays(today, 24)), metodo: 'zelle',        nota: 'Pago cuota 3' },
    { id: 'pg4',  prestamoId: 'p2', clienteId: 'c1', monto: 7200,  fecha: fmt(subDays(today, 110)), metodo: 'efectivo',    nota: '' },
    { id: 'pg5',  prestamoId: 'p2', clienteId: 'c1', monto: 7200,  fecha: fmt(subDays(today, 80)), metodo: 'efectivo',     nota: '' },
    { id: 'pg6',  prestamoId: 'p2', clienteId: 'c1', monto: 7200,  fecha: fmt(subDays(today, 50)), metodo: 'transferencia', nota: 'Pago final' },
    { id: 'pg7',  prestamoId: 'p3', clienteId: 'c2', monto: 30000, fecha: fmt(subDays(today, 45)), metodo: 'efectivo',     nota: 'Cuota 1' },
    { id: 'pg8',  prestamoId: 'p3', clienteId: 'c2', monto: 30000, fecha: fmt(subDays(today, 15)), metodo: 'cashapp',      nota: 'Cuota 2' },
    { id: 'pg9',  prestamoId: 'p4', clienteId: 'c3', monto: 4200,  fecha: fmt(subDays(today, 40)), metodo: 'efectivo',     nota: '' },
    { id: 'pg10', prestamoId: 'p4', clienteId: 'c3', monto: 4200,  fecha: fmt(subDays(today, 25)), metodo: 'efectivo',     nota: '' },
    { id: 'pg11', prestamoId: 'p4', clienteId: 'c3', monto: 4200,  fecha: fmt(subDays(today, 10)), metodo: 'zelle',        nota: '' },
    { id: 'pg12', prestamoId: 'p7', clienteId: 'c2', monto: 29333, fecha: fmt(subDays(today, 170)), metodo: 'efectivo',    nota: '' },
    { id: 'pg13', prestamoId: 'p7', clienteId: 'c2', monto: 29333, fecha: fmt(subDays(today, 140)), metodo: 'efectivo',    nota: '' },
    { id: 'pg14', prestamoId: 'p7', clienteId: 'c2', monto: 29334, fecha: fmt(subDays(today, 110)), metodo: 'transferencia', nota: 'Pago final' },
    { id: 'pg15', prestamoId: 'p6', clienteId: 'c5', monto: 1500,  fecha: fmt(subDays(today, 23)), metodo: 'efectivo',     nota: 'Primera cuota' },
  ]

  return { clientes, prestamos, pagos }
}
